---
kind: pipeline
name: build-image-amd64

platform:
  arch: amd64
  os: linux

workspace:
  path: /drone/src

steps:
- name: build-latest
  image: plugins/docker
  settings:
    repo: lha-on-docker
    tags:
      - latest-amd64
    cache_from:
      - lha-on-docker:latest-amd64
    dockerfile: Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: build-image-arm64

platform:
  arch: arm64
  os: linux

workspace:
  path: /drone/src

steps:
- name: build-latest
  image: plugins/docker
  settings:
    repo: lha-on-docker
    tags:
      - latest-arm64
    cache_from:
      - lha-on-docker:latest-arm64
    dockerfile: Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push

---
kind: pipeline
name: manifest-latest

steps:
- name: manifest-base-latest
  image: plugins/manifest
  settings:
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
    target: lha-on-docker:latest
    template: lha-on-docker:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

depends_on:
  - build-image-amd64
  - build-image-arm64

trigger:
  branch:
    include:
    - master
  event:
    include:
    - push


